spacing = 1
padding = 0
hide_ascii = false
prefer_small_ascii = true
separator = ""

[palette]
type = "Light"
glyph = "󱟱 "
visible = true

[bar]
glyph = "♥ "
symbol_open = '['
symbol_close = ']'
visible = false
hide_delimiters = true

[box]
title = " Fetch "
border = "rounded"
visible = true

[custom_ascii]
color = "White"
path = "~/.config/macchina/themes/ascii/kitty"