###
###                     ---   Flavours Config   ---      
### Rename subtemplates and gtk theme to desired layout style when configuring
### 

## -- hyprland --
#[[items]]
#file = "~/.config/hypr/theme/theme.conf"
#template = "hyprland"
#subtemplate = "clean"
#rewrite = true


## -- waterfox --
#[[items]]
#file = "~/.waterfox/ywnasjr6.default-release/chrome/userContent.css"
#template = "waterfox"
#rewrite = false
#start= "/* Start flavours */"
#end = "/* End flavours */"


## -- kitty --
#[[items]]
#file = "~/.config/kitty/kitty.conf"
#template = "kitty"
#subtemplate = "clean"
#rewrite = true
#hook = "kitty kill -SIGUSR1 $(pidof kitty)"


## -- starship --
#[[items]]
#file = "~/.config/starship.toml"
#template = "starship"
#subtemplate = "clean"
#rewrite = true


## -- gtk --
# gtk3
[[item]]
file = "~/.themes/solid_gtk/gtk-3.0/colors.css"
template = "gtk"
subtemplate = "gtk-3"
rewrite = true

# gtk2
[[item]]
file = "~/.themes/solid_gtk/gtk-2.0/gtkrc"
template = "gtk"
subtemplate = "gtk-2"
rewrite = true
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme solid_gtk && gsettings set org.gnome.desktop.interface font-name \"JetBrainsMono Nerd Font\""


## -- tofi --
#[[items]]
#file = "~/.config/tofi/config"
#template = "tofi"
#subtemplate = "clean"
#rewrite = true


## -- waybar --
# config
#[[items]]
#file = "~/.config/waybar/config"
#template = "waybar"
#subtemplate = "config-clean"
#rewrite = true
#hook = "killall waybar; waybar & disown"

# css
#[[items]]
#file = "~/.config/waybar/style.css"
#template = "waybar"
#subtemplate = "css-clean"
#rewrite = true


## -- swaync --
# config
[[items]]
file = "~/.config/swaync/config.json"
template = "swaync"
subtemplate = "config-clean"
rewrite = true
hook = "swaync-client -R"

# css
[[items]]
file = "~/.config/swaync/style.css"
template = "swaync"
subtemplate = "css-clean"
rewrite = true
hook = "swaync-client -rs"


## -- swaylock --
#[[items]]
#file = "~/.config/swaylock/config"
#template = "swaylock"
#subtemplate = "clean"
#rewrite = true


# -- swaybg --
#[[items]]
#file = "~/.config/hypr/theme/swaybg.conf"
#template = "swaybg"
#rewrite = true


