# waybar
[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
subtemplate = "css_pixel"
rewrite = true

[[items]]
file = "~/.config/waybar/config"
template = "waybar"
subtemplate = "config_pixel"
rewrite = true
hook = "killall waybar; waybar & disown"

# swaync
[[items]]
file = "~/.config/swaync/colors.css"
template = "gtk"
subtemplate = "css"
rewrite = true
hook = "swaync-client -rs"

# tofi
[[items]]
file = "~/.config/tofi/config"
template = "tofi"
subtemplate = "pixel"
rewrite = true

# gtk
[[item]]
file = "~/.themes/solid_gtk/gtk-3.0/colors.css"
template = "gtk"
subtemplate = "gtk-3"
rewrite = true

[[item]]
file = "~/.themes/solid_gtk/gtk-2.0/gtkrc"
template = "gtk"
subtemplate = "gtk-2"
rewrite = true
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme solid_gtk && gsettings set org.gnome.desktop.interface font-name \"JetBrainsMono Nerd Font\""

# vim

# kitty
[[items]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
subtemplate = "pixel"
rewrite = true
hook = "kitty kill -SIGUSR1 $(pidof kitty)"

# waterfox
[[items]]
file = "~/.waterfox/ywnasjr6.default-release/chrome/userContent.css"
template = "waterfox"
rewrite = false
start= "/* Start flavours */"
end = "/* End flavours */"

# swaylock
[[items]]
file = "~/.config/swaylock/config"
template = "swaylock"
subtemplate = "pixel"
rewrite = true

# hyprland
[[items]]
file = "~/.config/hypr/theme/theme.conf"
template = "hyprland"
subtemplate = "pixel"
rewrite = true

# starship
[[items]]
file = "~/.config/starship.toml"
template = "starship"
subtemplate = "pixel"
rewrite = true