###
###                     ---   Flavours Config   ---      
### Rename subtemplates and gtk theme to desired layout style when configuring
### 

## -- hyprland --
[[items]]
file = "~/.config/hypr/theme/theme.conf"
template = "hyprland"
subtemplate = "dev"
rewrite = true


## -- waterfox --
[[items]]
file = "~/.waterfox/ywnasjr6.default-release/chrome/userContent.css"
template = "waterfox"
rewrite = false
start= "/* Start flavours */"
end = "/* End flavours */"


## -- kitty --
[[items]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
subtemplate = "dev"
rewrite = true
hook = "kitty kill -SIGUSR1 $(pidof kitty)"


## -- starship --
[[items]]
file = "~/.config/starship.toml"
template = "starship"
subtemplate = "dev"
rewrite = true


## -- Neovim --
[[items]]
file = "~/.config/nvim/colors/default-base16.lua"
template = "neovim"
rewrite = true


## -- gtk --
# gtk3
# solid_gtk
[[item]]
file = "~/.themes/sharp_gtk/gtk-3.0/colors.css"
template = "gtk"
subtemplate = "gtk-3"
rewrite = true

# gtk2
[[item]]
file = "~/.themes/sharp_gtk/gtk-2.0/gtkrc"
template = "gtk"
subtemplate = "gtk-2"
rewrite = true

# apply gtk theme
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme sharp_gtk && gsettings set org.gnome.desktop.interface font-name \"Mononoki Nerd Font 10\""


## -- tofi --
[[items]]
file = "~/.config/tofi/config"
template = "tofi"
subtemplate = "dev"
rewrite = true


# -- waybar --
# config
[[items]]
file = "~/.config/waybar/config"
template = "waybar"
subtemplate = "config-dev"
rewrite = true

# css
[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
subtemplate = "css-dev"
rewrite = true

# reload waybar
hook = "killall waybar; waybar & disown"


## -- swaync --
# config
[[items]]
file = "~/.config/swaync/config.json"
template = "swaync"
subtemplate = "config-dev"
rewrite = true
hook = "swaync-client -R"

# css
[[items]]
file = "~/.config/swaync/style.css"
template = "swaync"
subtemplate = "css-dev"
rewrite = true

# reload swaync
hook = "swaync-client -rs"


## -- swaylock --
[[items]]
file = "~/.config/swaylock/config"
template = "swaylock"
subtemplate = "dev"
rewrite = true


## -- swaybg --
[[items]]
file = "~/.config/hypr/theme/swaybg.conf"
template = "swaybg"
rewrite = true


