format = """
[](#313244)\
$os\
$username\
$directory\
[](fg:#313244 bg:#a6e3a1)\
$git_branch\
$git_status\
[▓▒░](#a6e3a1)
$character\
"""

# Disable the blank line at the start of the prompt
#add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#313244 fg:#cba6f7"
style_root = "bg:#313244 fg:#cba6f7"
format = '[ $user ](bold $style)'
disabled = false

[directory]
style = "bg:#313244 fg:#cba6f7"
format = "[  $path ](bold $style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#a6e3a1 fg:#181825"
format = '[ $symbol $branch ](bold $style)'

[git_status]
style = "bg:#a6e3a1 fg:#181825"
format = '[$all_status$ahead_behind ](bold $style)'

[character]
success_symbol = '[](bold cdd6f4) '
error_symbol = '[ ✗](#cba6f7) '

[fill]
symbol = '-'
style = 'fg:#181825'

[battery]
full_symbol = '󱈑 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
format = '[ $symbol]($style)'

[[battery.display]]
threshold = 20
style = 'bold #f38ba8 bg:#313244'

[[battery.display]]
threshold = 50
style = 'bold #f9e2af bg:#313244'

[[battery.display]]
threshold = 100
style = 'bold #a6e3a1 bg:#313244'


[time]
disabled = false
style = 'bg:#313244 fg:#cba6f7'
format = '[$time ](bold $style)'