##########################################
## Tabs
##########################################


# There are more style options and strings to configure
# the tab-bar theme.

##########################################
## File List - Selections
##########################################

# Selected files (standard selection)
[selection]
fg = "red"
bold = true

# Files selected in current visual mode
[visual_mode_selection]
fg = "red"
bold = true

[selection.prefix]
prefix = "   "
size = 2

##########################################
## File List - System File Types
##########################################

# Basic style, used for regular files (and also device files and FIFOs)
[regular]
fg = "gray"

# For directories
[directory]
fg = "white"
bold = true

# For symbolic links
[link]
fg = "cyan"
bold = true

# For socket files
[socket]
fg = "light_magenta"
bold = true

##########################################
## File List - Exceptional Files
##########################################

# Files marked as executable
[executable]
fg = "light_green"
bold = true

# Invalid symbolic links (pointing to non-existing target)
[link_invalid]
fg = "red"
bold = true

##########################################
## File list - Override style by extension
##########################################
# This sections allows to override the basic 
# style with a specific style for the file's
# extension.

[ext]

bmp.fg = "blue"
gif.fg = "blue"
heic.fg = "blue"
jpg.fg = "blue"
jpeg.fg = "blue"
pgm.fg = "blue"
png.fg = "blue"
ppm.fg = "blue"
svg.fg = "blue"

wav.fg = "green"
flac.fg = "green"
mp3.fg = "green"
amr.fg = "green"

avi.fg = "blue"
flv.fg = "blue"
m3u.fg = "blue"
m4a.fg = "blue"
m4v.fg = "blue"
mkv.fg = "blue"
mov.fg = "blue"
mp4.fg = "blue"
mpg.fg = "blue"
rmvb.fg = "blue"
webm.fg = "blue"
wmv.fg = "blue"

7z.fg = "yellow"
bz2.fg = "yellow"
gz.fg = "yellow"
rar.fg = "yellow"
tar.fg = "yellow"
tgz.fg = "yellow"
xz.fg = "yellow"
zip.fg = "yellow"




[tabs]

[tabs.chars]
divider = "  "
active_prefix = "[ "
active_postfix = " ]"
inactive_prefix = ""
inactive_postfix = ""

# front arrow
scroll_front_prefix = ""
scroll_front_postfix = "▓▒░ "
scroll_front_prestring = " "
scroll_front_poststring = " "

# back arrow
scroll_back_prefix = " ░▒▓"
scroll_back_postfix = ""
scroll_back_prestring = " "
scroll_back_poststring = " "

[tabs.styles]

[tabs.styles.active]
fg = "white"
bg = "reset"
bold = true

[tabs.styles.active_prefix]
fg = "white"
bg = "reset"

[tabs.styles.inactive]
fg = "magenta"
bg = "reset"

[tabs.styles.inactive_prefix]
fg = "black"
bg = "reset"

# front arrow
[tabs.styles.scroll_front]
fg = "black"
bg = "gray"
bold = true

[tabs.styles.scroll_front_prefix]
fg = "gray"
bg = "reset"

[tabs.styles.scroll_front_postfix]
invert = false

# back arrow
[tabs.styles.scroll_back]
fg = "black"
bg = "gray"
bold = true

[tabs.styles.scroll_back_prefix]
fg = "gray"
bg = "reset"

[tabs.styles.scroll_back_postfix]
invert = false
